---
# Main tasks file.
- name: Main | Load distribution relevant variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Main | Include install.yml
  ansible.builtin.include_tasks: "./install.yml"
- name: Main | Include config.yml
  ansible.builtin.include_tasks: "./config.yml"
